package gehring.simon.kvmn.model

import javax.xml.bind.annotation.XmlAccessType
import javax.xml.bind.annotation.XmlAccessorType
import javax.xml.bind.annotation.XmlElement
import javax.xml.bind.annotation.XmlType


/**
 * This elements describes all that pertains to distribution for a project. It is
 * primarily used for deployment of artifacts and the site produced by the build.
 *
 * Java-Klasse für DistributionManagement complex type.
 *
 * Das folgende Schemafragment gibt den erwarteten Content an, der in dieser Klasse enthalten ist.
 *
 * <pre>
 * &lt;complexType name="DistributionManagement">
 * &lt;complexContent>
 * &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 * &lt;all>
 * &lt;element name="repository" type="{http://maven.apache.org/POM/4.0.0}DeploymentRepository" minOccurs="0"/>
 * &lt;element name="snapshotRepository" type="{http://maven.apache.org/POM/4.0.0}DeploymentRepository" minOccurs="0"/>
 * &lt;element name="site" type="{http://maven.apache.org/POM/4.0.0}Site" minOccurs="0"/>
 * &lt;element name="downloadUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;element name="relocation" type="{http://maven.apache.org/POM/4.0.0}Relocation" minOccurs="0"/>
 * &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 * &lt;/all>
 * &lt;/restriction>
 * &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DistributionManagement", namespace = "http://maven.apache.org/POM/4.0.0", propOrder = [])
data class DistributionManagement(

  /**
   * Information needed to deploy the artifacts generated by the project to a
  remote repository.
   */
  @XmlElement(namespace = "http://maven.apache.org/POM/4.0.0")
  val repository: DeploymentRepository,
  /**
   * Where to deploy snapshots of artifacts to. If not given, it defaults to the
  &lt;code&gt;repository&lt;/code&gt; element.
   */
  @XmlElement(namespace = "http://maven.apache.org/POM/4.0.0")
  val snapshotRepository: DeploymentRepository,
  /**
   * Information needed for deploying the web site of the project.
   */
  @XmlElement(namespace = "http://maven.apache.org/POM/4.0.0")
  val site: Site,
  /**
   * The URL of the project&apos;s download page. If not given users will be
  referred to the homepage given by &lt;code&gt;url&lt;/code&gt;.
  This is given to assist in locating artifacts that are not in the repository due to
  licensing restrictions.
   */
  @XmlElement(namespace = "http://maven.apache.org/POM/4.0.0")
  val downloadUrl: String,
  /**
   * Relocation information of the artifact if it has been moved to a new group ID
  and/or artifact ID.
   */
  @XmlElement(namespace = "http://maven.apache.org/POM/4.0.0")
  val relocation: Relocation,
  /**
   * Gives the status of this artifact in the remote repository.
  This must not be set in your local project, as it is updated by
  tools placing it in the reposiory. Valid values are: &lt;code&gt;none&lt;/code&gt; (default),
  &lt;code&gt;converted&lt;/code&gt; (repository manager converted this from an Maven 1 POM),
  &lt;code&gt;partner&lt;/code&gt;
  (directly synced from a partner Maven 2 repository), &lt;code&gt;deployed&lt;/code&gt; (was deployed from a Maven 2
  instance), &lt;code&gt;verified&lt;/code&gt; (has been hand verified as correct and final).
   */
  @XmlElement(namespace = "http://maven.apache.org/POM/4.0.0")
  val status: String)
